### ISSUE TITLE
Block Placement Duplication

### ISSUE THREAD

**Issue by Cazadorsniper** [IStrikeboomI/CobblestoneSemantics#5]
Version: 1.2
When placing Cobblestone Melter and Cobblestone Generators they seem to duplicate and never remove themselves from the inventory until they are placed into a chest or other storage. Other blocks maybe affected by this.

Also the Melter has a Visual bug when the lava is bucketed out, the GUI still thinks there is still lava in it but it actually isn't there.

**Comment by IStrikeboomI** [comment]
Fixed visual bug with https://github.com/IStrikeboomI/CobblestoneSemantics/commit/c0f192e3231c8ee9f165452a454467cfbe151640

**Comment by IStrikeboomI** [comment]
Fixed block duplication glitch with ed2397ca60c49d943683b657988b454332cd3ea7
